name: math_assessment
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.3
  shared_preferences: ^2.2.3
  riverpod_annotation: ^3.0.0-dev.3
  email_validator: '^3.0.0'
  http: ^1.2.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0
  audioplayers: ^5.2.1
  collection: ^1.18.0
  hooks_riverpod: ^3.0.0-dev.3
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  
  build_runner:
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/audios/en/
    - assets/question_data.json
